### 登录
GET url HTTP/1.1

{
  "status": "1",
  "msg": "登陆成功"
}

### 新闻请求
GET url HTTP/1.1

{
  "id": "001",
  "title": "标题xxx",
  "content": "内容xxxxxxx"
}
### 新闻添加
POST http://172.30.86.195:8000/files HTTP/1.1
Content-Type: multipart/form-data

{
  "title": "xx",
  "content": "xxxxxxxxxx"
}